version: '3.8'

services:
  web:
    build: .
    container_name: resume
    restart: unless-stopped
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.juan-website.rule=Host(`juan.garces.xyz`)"
      - "traefik.http.routers.juan-website.entrypoints=websecure"
      - "traefik.http.routers.juan-website.tls=true"
      - "traefik.http.services.juan-website.loadbalancer.server.port=80"

networks:
  traefik-public:
    external: true